CREATE TABLE MATHANG
(
	[MAMH] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [TENMH] NVARCHAR(100) NOT NULL, 
    [DVT] NVARCHAR(100) NOT NULL, 
    [NGAYNHAP] DATE NOT NULL, 
    [DONGIA] INT NOT NULL, 
    [SOLUONG] INT NOT NULL, 
    [HINHANH] IMAGE NOT NULL, 
    [MANCC] VARCHAR(50) NOT NULL
)
